### ISSUE TITLE
扫描的时候报错，找不到TypeHandler：Caused by: java.lang.ClassNotFoundException: Cannot find class: com.taobao.spring.typehandler.UserStatusTypeHandler

### ISSUE THREAD

**Issue by index3389** [donhui/sonar-mybatis#12]
具体的报错日志，我上传到github了，地址是：
https://github.com/index3389/springboot2-mybatis-sonar/blob/master/mvn.logs.txt

完整的项目也上传到github了，项目可以正常启动，正常运行，但是，使用sonar-mybatis扫描就报错
Caused by: java.lang.ClassNotFoundException: Cannot find class: com.taobao.spring.typehandler.UserStatusTypeHandler

麻烦楼主帮忙看看，
项目地址是：https://github.com/index3389/springboot2-mybatis-sonar
直接clone下来就可以扫描看看了

**Comment by donhui** [comment]
@index3389 
你的 Mapper 文件中，有个SQL是下面这样
`select * from user3 where status=#{status,typeHandler=com.taobao.spring.typehandler.UserStatusTypeHandler}`
为啥有句 typeHandler=com.taobao.spring.typehandler.UserStatusTypeHandler 呢？

**Comment by index3389** [comment]
> @index3389
> 你的 Mapper 文件中，有个SQL是下面这样
> `select * from user3 where status=#{status,typeHandler=com.taobao.spring.typehandler.UserStatusTypeHandler}`
> 为啥有句 typeHandler=com.taobao.spring.typehandler.UserStatusTypeHandler 呢？

因为参数类型是枚举。必须要有一个TypeHandler去解析这个枚举。
这样做是没有问题的，程序可正常运行

**Comment by index3389** [comment]
现在的问题是，明明有这个TypeHandler，为什么找不到？

**Comment by donhui** [comment]
> 现在的问题是，明明有这个TypeHandler，为什么找不到？

处理的时候，没有去加载这个类（没有想到很好的方式处理）
有个 XML 预处理，就是删掉无法处理的一些元素（如：resultMap、parameterType、resultType）
你遇到的这个问题，如果按这个思路，应该也需要想办法做个预处理，删掉 typeHandler

**Comment by index3389** [comment]
> > 现在的问题是，明明有这个TypeHandler，为什么找不到？
> 
> 处理的时候，没有去加载这个类（没有想到很好的方式处理）
> 有个 XML 预处理，就是删掉无法处理的一些元素（如：resultMap、parameterType、resultType）
> 你遇到的这个问题，如果按这个思路，应该也需要想办法做个预处理，删掉 typeHandler

现在的问题是，公司其他人很喜欢这样用，我现在只是搭建了一个sonar服务，集成mybatis扫描，我不可能去改别人的代码

**Comment by donhui** [comment]
> > > 现在的问题是，明明有这个TypeHandler，为什么找不到？
> > 
> > 
> > 处理的时候，没有去加载这个类（没有想到很好的方式处理）
> > 有个 XML 预处理，就是删掉无法处理的一些元素（如：resultMap、parameterType、resultType）
> > 你遇到的这个问题，如果按这个思路，应该也需要想办法做个预处理，删掉 typeHandler
> 
> 现在的问题是，公司其他人很喜欢这样用，我现在只是搭建了一个sonar服务，集成mybatis扫描，我不可能去改别人的代码

我的意思是插件如果要解决这个问题，得想办法在预处理 mapper xml 文件时，删掉 typeHandler

**Comment by donhui** [comment]
@index3389 
可以试下这个版本：
https://github.com/donhui/sonar-mybatis/releases/download/1.0.5-alpha/sonar-mybatis-plugin-1.0.5-SNAPSHOT.jar

**Comment by index3389** [comment]
> @index3389
> 可以试下这个版本：
> https://github.com/donhui/sonar-mybatis/releases/download/1.0.5-alpha/sonar-mybatis-plugin-1.0.5-SNAPSHOT.jar

非常感谢，楼主解决问题的速度很快。
但是，我看你改的方式，直接用的是替换
String text = element.getText();
text = text.replaceAll(",[\\s]*typeHandler=[.*A-Za-z0-9_=,]*}","}");
text = text.replaceAll(",[\\s]*javaType=[.A-Za-z0-9_=,]*}","}");
text = text.replaceAll(",[\\s]*jdbcType=[.A-Za-z0-9_=,]*}","}");
element.setText(text)

我不建议这样改，因为可能会造成其他的问题。
建议还是找出引起ClassNotFoundException的根本原因，为什么存在的类，却找不到

**Comment by donhui** [comment]
> > @index3389
> > 可以试下这个版本：
> > https://github.com/donhui/sonar-mybatis/releases/download/1.0.5-alpha/sonar-mybatis-plugin-1.0.5-SNAPSHOT.jar
> 
> 非常感谢，楼主解决问题的速度很快。
> 但是，我看你改的方式，直接用的是替换
> String text = element.getText();
> text = text.replaceAll(",[\s]*typeHandler=[._A-Za-z0-9_=,]_}","}");
> text = text.replaceAll(",[\s]_javaType=[.A-Za-z0-9_=,]_}","}");
> text = text.replaceAll(",[\s]_jdbcType=[.A-Za-z0-9_=,]_}","}");
> element.setText(text)
> 
> 我不建议这样改，因为可能会造成其他的问题。
> 建议还是找出引起ClassNotFoundException的根本原因，为什么存在的类，却找不到

之前也用的替换，这个替换不会修改原来的 mybatis mapper xml 文件，它会生成一个新的 mapper xml 文件。
至于类找不到，那是因为它们没有被加载到 classpath 中。

**Comment by donhui** [comment]
> > @index3389
> > 可以试下这个版本：
> > https://github.com/donhui/sonar-mybatis/releases/download/1.0.5-alpha/sonar-mybatis-plugin-1.0.5-SNAPSHOT.jar
> 
> 非常感谢，楼主解决问题的速度很快。
> 但是，我看你改的方式，直接用的是替换
> String text = element.getText();
> text = text.replaceAll(",[\s]*typeHandler=[._A-Za-z0-9_=,]_}","}");
> text = text.replaceAll(",[\s]_javaType=[.A-Za-z0-9_=,]_}","}");
> text = text.replaceAll(",[\s]_jdbcType=[.A-Za-z0-9_=,]_}","}");
> element.setText(text)
> 
> 我不建议这样改，因为可能会造成其他的问题。
> 建议还是找出引起ClassNotFoundException的根本原因，为什么存在的类，却找不到

在 maven 上下文执行 sonar:sonar ，并没有加载你要分析的项目的 classpath
它的 classpath 为：
`/xxx/apache-maven-3.5.0/boot/plexus-classworlds-2.5.2.jar`

**Comment by index3389** [comment]
> > > @index3389
> > > 可以试下这个版本：
> > > https://github.com/donhui/sonar-mybatis/releases/download/1.0.5-alpha/sonar-mybatis-plugin-1.0.5-SNAPSHOT.jar
> > 
> > 
> > 非常感谢，楼主解决问题的速度很快。
> > 但是，我看你改的方式，直接用的是替换
> > String text = element.getText();
> > text = text.replaceAll(",[\s]*typeHandler=[._A-Za-z0-9_=,]_}","}");
> > text = text.replaceAll(",[\s]_javaType=[.A-Za-z0-9_=,]_}","}");
> > text = text.replaceAll(",[\s]_jdbcType=[.A-Za-z0-9_=,]_}","}");
> > element.setText(text)
> > 我不建议这样改，因为可能会造成其他的问题。
> > 建议还是找出引起ClassNotFoundException的根本原因，为什么存在的类，却找不到
> 
> 在 maven 上下文执行 sonar:sonar ，并没有加载你要分析的项目的 classpath
> 它的 classpath 为：
> `/xxx/apache-maven-3.5.0/boot/plexus-classworlds-2.5.2.jar`

为什么sonar在扫描某个项目的时候，不把这个项目加入到classpath中去？
如果是按你说的，是maven没有加载，那sonar就应该自己自定义一个classloader，自己去把项目加载到classpath

**Comment by donhui** [comment]
@index3389 
那sonar就应该自己自定义一个classloader，自己去把项目加载到classpath
-----
这个也想过，比较麻烦的
比如：
怎么知道加载哪些类或库？这些类或库在哪里？
让用户自己指定，还是插件自己猜？
让用户传的话，要增加配置，增加了插件使用的复杂度
插件自己猜的话，如果用户使用不同构建工具（如：Maven/Gradle/Ant……）时该如何处理呢？感觉又不太靠谱

**Comment by index3389** [comment]
我看了一下插件扫描的代码，里面有用到mybatis的XMLMapperBuilder类去parse xml文件，在parse的时候，会去检查TypeHandler是否存在。
插件能否改成不要用XMLMapperBuilder类去parse xml文件，而是自己去parse xml文件，就不会报ClassNotFoundException了

**Comment by donhui** [comment]
> 我看了一下插件扫描的代码，里面有用到mybatis的XMLMapperBuilder类去parse xml文件，在parse的时候，会去检查TypeHandler是否存在。
> 插件能否改成不要用XMLMapperBuilder类去parse xml文件，而是自己去parse xml文件，就不会报ClassNotFoundException了

要是我自己用 Dom 解析，肯定没 MyBatis 解析的好

**Comment by donhui** [comment]
发布了新版本：1.0.5
这个问题解决了，就先关掉了
如果再出现类似问题，可以重新打开这个 Issue，或者重新建 Issue
