### ISSUE TITLE
java.lang.IllegalArgumentException : Mapped Statements collection already contains value

### ISSUE THREAD

**Issue by radboud-asselman** [donhui/sonar-mybatis#13]
We are tring to run a Sonar scan via Maven an dJenkins. In Sonar we activated the Sonar-mybatis plugin. The following error occurs:

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project xxx: Error parsing Mapper XML. The XML location is 'file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml-reduced.xml]'. Cause: java.lang.IllegalArgumentException: Mapped Statements collection already contains value for nl.xxx.xxx.logic.additionalinformation.persistence.mapper.AdditionalInformationMapper.getClientAdditionalInformation. please check file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml] and file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml-reduced.xml] -> [Help 1]

Can anyone help me?

**Comment by donhui** [comment]
> We are tring to run a Sonar scan via Maven an dJenkins. In Sonar we activated the Sonar-mybatis plugin. The following error occurs:
> 
> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project xxx: Error parsing Mapper XML. The XML location is 'file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml-reduced.xml]'. Cause: java.lang.IllegalArgumentException: Mapped Statements collection already contains value for nl.xxx.xxx.logic.additionalinformation.persistence.mapper.AdditionalInformationMapper.getClientAdditionalInformation. please check file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml] and file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml-reduced.xml] -> [Help 1]
> 
> Can anyone help me?
The plugin will generate some temp xml files which suffix are `-reduced.xml`, and will remove them if the maven task executes successfully. But if failed,  the temp file will not be removed.
Please make sure your sonar-mybatis  plugin version is latest(now is 1.0.4).
And then running the Jenkins Job with a clean workspace.
If it still has exception, please provide the message again.

**Comment by donhui** [comment]
> We are tring to run a Sonar scan via Maven an dJenkins. In Sonar we activated the Sonar-mybatis plugin. The following error occurs:
> 
> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project xxx: Error parsing Mapper XML. The XML location is 'file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml-reduced.xml]'. Cause: java.lang.IllegalArgumentException: Mapped Statements collection already contains value for nl.xxx.xxx.logic.additionalinformation.persistence.mapper.AdditionalInformationMapper.getClientAdditionalInformation. please check file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml] and file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\additionalinformation\persistence\mapper\AdditionalInformationMapper.xml-reduced.xml-reduced.xml] -> [Help 1]
> 
> Can anyone help me?

The plugin will generate some temp xml files which suffix are -reduced.xml, and will remove them if the maven task executes successfully. But if failed, the temp file will not be removed.
Please make sure your sonar-mybatis plugin version is latest(now is 1.0.4).
And then running the Jenkins Job with a clean workspace.
If it still has exception, please provide the message again.

**Comment by radboud-asselman** [comment]
That's it. Temp file is not removed. Only the sonar scan returns other error. I will create a new issue.
