### ISSUE TITLE
java.lang.ClassNotFoundException: Cannot find class

### ISSUE THREAD

**Issue by radboud-asselman** [donhui/sonar-mybatis#14]
Hi,

Running the Sonar scan gives the following error:
[INFO] handle mybatis mapper xml:/D:/jenkins_home/jobs/xxx/workspace/xxx/xxx.logic/src/nl/xxx/xxx/logic/applicationsettings/persistence/mapper/ApplicationSettingsMapper.xml
[INFO] 0/0 source files have been analyzed
[INFO] handle mybatis mapper xml:/D:/jenkins_home/jobs/xxx/workspace/xxx/xxx.logic/src/nl/xxx/xxx/logic/authentication/persistence/mapper/AuthenticationMapper.xml
[INFO] handle mybatis mapper xml:/D:/jenkins_home/jobs/xxx/workspace/xxx/xxx.logic/src/nl/xxx/xxx/logic/authorization/persistence/mapper/AuthorizationMapper.xml
[INFO] handle mybatis mapper xml:/D:/jenkins_home/jobs/xxx/workspace/xxx/xxx.logic/src/nl/xxx/xxx/logic/bluebutton/persistence/mapper/BlueButtonMapper.xml
[INFO] handle mybatis mapper xml:/D:/jenkins_home/jobs/xxx/workspace/xxx/xxx.logic/src/nl/xxx/xxx/logic/calendar/persistence/mapper/CalendarMapper.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for xxx 4.15-SNAPSHOT:
[INFO] 
[INFO] xxx ............................................. FAILURE [05:11 min]
[INFO] xxxJavaCore ..................................... SUCCESS [01:07 min]
[INFO] xxx ....................................... SUCCESS [  0.071 s]
[INFO] xxxDomainModels ........................... SUCCESS [  8.313 s]
[INFO] xxxLogic .................................. SUCCESS [ 42.867 s]
[INFO] xxxPresentation ........................... SUCCESS [ 24.642 s]
[INFO] xxxWeb .................................... SUCCESS [ 15.449 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:57 min
[INFO] Finished at: 2019-09-11T12:35:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project xxx: Error parsing Mapper XML. The XML location is 'file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\calendar\persistence\mapper\CalendarMapper.xml-reduced.xml]'. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'CustomBooleanTypeHandler'.  Cause: java.lang.ClassNotFoundException: Cannot find class: CustomBooleanTypeHandler -> [Help 1]

Versions:
Sonar 7.9.1
Sonar plugins all updated, mybatis=1.0.4
Maven 3.6.1

Some of the handlers are scanned before the error. Please advise.

**Comment by donhui** [comment]
@radboud-asselman Can you provide the MyBatis Mapper XML file which use `xxx` instead of  the sensitive message?

**Comment by donhui** [comment]
@radboud-asselman I release a new SNNAPSHOT version, you can download it and try again, and I need your feedback. 
Thanks~
https://github.com/donhui/sonar-mybatis/releases/download/1.0.5-alpha/sonar-mybatis-plugin-1.0.5-SNAPSHOT.jar

**Comment by radboud-asselman** [comment]
Yes! The 1.0.5 snapshot version works! Thank you for the quick response. Keep up the good work!
