### ISSUE TITLE
java.lang.ClassNotFoundException: Cannot find class: JsonHandler

### ISSUE THREAD

**Issue by radboud-asselman** [donhui/sonar-mybatis#16]
Hi,

@donhui helped me with this issue: https://github.com/donhui/sonar-mybatis/issues/14, but scanning a new project gives us a new error.

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project caress: Error parsing Mapper XML. The XML location is 'file [D:\jenkins_home\jobs\xxx\workspace\xxx\xxx.logic\src\nl\xxx\xxx\logic\event\persistence\mapper\EventMapper.xml-reduced.xml]'. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'JsonHandler'.  Cause: java.lang.ClassNotFoundException: Cannot find class: JsonHandler -> [Help 1]

Is this also a bug?

**Comment by donhui** [comment]
@radboud-asselman Thanks for your feed, can you provide the related MyBatis Mapper file?

**Comment by radboud-asselman** [comment]
Hi,

I included the mapper file. Also the temporary generated file by the plugin.




[EventMapper.zip](https://github.com/donhui/sonar-mybatis/files/3605639/EventMapper.zip)

**Comment by donhui** [comment]
@radboud-asselman 
I want to know the content of the Mybatis Mapper file, it will help me troubleshooting. 
Can you provide it?
Thanks~

**Comment by donhui** [comment]
I have released the  version 1.0.5, the issue shoule be resloved.
