### ISSUE TITLE
不能用webhook

### ISSUE THREAD

**Issue by zhuduotao** [donhui/sonar-mybatis#19]
sonarqube 8.0
在配置了webhook的情况下,插件会产生如下错误
```
java.lang.AbstractMethodError: Receiver class org.sonarsource.plugins.mybatis.hooks.DisplayQualityGateStatus does not define or inherit an implementation of the resolved method 'abstract java.lang.String getDescription()' of interface org.sonar.api.ce.posttask.PostProjectAnalysisTask
```
导致webhook中断

**Comment by donhui** [comment]
这个 webhook 在哪里配置的呢？可以提供个截图么？

**Comment by donhui** [comment]
@zhuduotao 
计划发个新版本修复下，sonarqube 8.0 修改了PostProjectAnalysisTask，引起不兼容
这个插件本身也没用 hooks  的功能，计划去掉相关代码

**Comment by donhui** [comment]
@zhuduotao 
你可以用下 1.0.6 版本
https://github.com/donhui/sonar-mybatis/releases/download/1.0.6/sonar-mybatis-plugin-1.0.6.jar
