### ISSUE TITLE
[WARNING] org.dom4j.DocumentException: Connection timed out: connect Nested exception: Connection timed out: connect

### ISSUE THREAD

**Issue by index3389** [donhui/sonar-mybatis#4]
[INFO] Java Test Files AST scan (done) | time=718ms
[INFO] Sensor JavaSquidSensor [java] (done) | time=4816ms
[INFO] Sensor MyBatisLint Sensor [mybatis]
[INFO] stmtIdExcludeList: []
[WARNING] org.dom4j.DocumentException: Connection timed out: connect Nested exception: Connection timed out: connect
[WARNING] org.dom4j.DocumentException: Connection timed out: connect Nested exception: Connection timed out: connect
[WARNING] org.dom4j.DocumentException: Connection timed out: connect Nested exception: Connection timed out: connect
[WARNING] org.dom4j.DocumentException: Connection timed out: connect Nested exception: Connection timed out: connect
[INFO] Sensor MyBatisLint Sensor [mybatis] (done) | time=84234ms
[INFO] Sensor JaCoCo XML Report Importer [jacoco]
[INFO] Sensor JaCoCo XML Report Importer [jacoco] (done) | time=4ms

为什么会有这个 [WARNING] org.dom4j.DocumentException: Connection timed out: connect Nested exception: Connection timed out: connect 的告警？

扫描的时候，要connect到哪里去

**Comment by donhui** [comment]
解析 xml 时候，会通过网络请求 DOCTYPE 中 的 dtd 文件
应该是你网络请求不到 dtd 文件，报 timeout 了

**Comment by donhui** [comment]
@index3389 
我改了代码，跳过了 dtd 校验
你可以手动下载下面版本的插件，确认下是否解决你的问题
https://github.com/donhui/sonar-mybatis/releases/tag/1.0.3-beta

**Comment by donhui** [comment]
@index3389 
我重新更新了下版本，如果之前下载了，还需要麻烦重新下载下，谢谢
https://github.com/donhui/sonar-mybatis/releases/tag/1.0.3-beta

**Comment by index3389** [comment]
> @index3389
> 我重新更新了下版本，如果之前下载了，还需要麻烦重新下载下，谢谢
> https://github.com/donhui/sonar-mybatis/releases/tag/1.0.3-beta

感谢
