### ISSUE TITLE
扫描过程中产生的-reduced.xml文件，扫描结束为什么不清理掉？

### ISSUE THREAD

**Issue by index3389** [donhui/sonar-mybatis#5]
我在本地扫描，扫描完了，项目工程里面就会产生-reduced.xml文件

每扫描一次，产生一批，扫描了几次，产生了好多-reduced.xml文件

扫描结束为什么不清理掉？

**Comment by donhui** [comment]
扫描成功的话会自动清理，如果因为报错导致扫描失败的话没有清理
